### ISSUE TITLE
What is your electricity file modelData.csv comes from?

### ISSUE THREAD

**Issue by hihihihiwsf** [oneday88/kdd2019deepTCN#1]
Hello, I'm reproducing your experiment of electricity part. I got the dataset from ttps://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014  , with the file type of txt.  I'd like to learn about what content is in  your file modelData.csv so that I can change the dataset to that frame. 
Thank you very much!

**Comment by oneday88** [comment]
Hi, glad to hear from you. I added an R script to the ec fold. You can easily generate the modelData.csv by  running the R script "basicPreprocess.R"

**Comment by hihihihiwsf** [comment]
Thanks for your the data generator file, and I met another error when I run the  bestPointHuber.py and other methods in TCNQuantile.
 It said that in the line 152 of the  file nnModels.py,     
Check failed: shape_assign(&(*in_shape)[i], dshape) Incompatible input shape: expected [512,168,0], got [512,336,1]
![image](https://user-images.githubusercontent.com/33193751/63922653-a8988e80-ca77-11e9-8f2c-bef099c0ce9d.png)

**Comment by hihihihiwsf** [comment]
It seems like the dimensions of reshaped x_num and input_store are not the same other than the appointed dim.
But when I chenged the function as 
output = nd.concat(input_store,x_num.reshape((input_store.shape[0],input_store.shape[1],-1)), dim=2) 
It got an error in the forward shape inconsistency.
Can you help you with this? Thank you very much!

**Comment by hihihihiwsf** [comment]
Besides , what's the difference among nnModels.py, nnModels-Copy1.py and newModels.py ?

**Comment by oneday88** [comment]
Hi, glad to hear  from you again. I update a new file bestPointHuber.ipynb, which taken the input pkl file "feature_prepare.pkl" resulting from  file "ec_feature_preprocess.ipynb" (instead for the original new_feature_prepare.pkl)

**Comment by hihihihiwsf** [comment]
Thank you for your reply ! My result of  ECPoint.py and ECPointHuber.py without changing any parameters in them have results of valid ND is 0.42 and 0.49, and valid NRMSE is 2.82 and 2.35  respectively, which are so much different with the result in your paper. Can you help me with this?

**Comment by oneday88** [comment]
CPU or GPU server?

**Comment by hihihihiwsf** [comment]
GPU

**Comment by oneday88** [comment]
Training loss and testing loss logs, please. 
If ND is about 0.42. It means the predictive result is just straight light and do not learn any patterns. I will re-check the codes next Monday.

**Comment by hihihihiwsf** [comment]
Do you mean this? 
[loss.zip](https://github.com/oneday88/kdd2019deepTCN/files/3558120/loss.zip)
I drawed the predicted first 400 values and the according true values, the result is:
 
![L1Loss(batch_axis=0, w=None)_model_2196287 8](https://user-images.githubusercontent.com/33193751/63990539-ef899100-cb16-11e9-907b-a5b6861c4afb.jpg)

Thank you very much!

**Comment by hihihihiwsf** [comment]
Hi, have you checked the code yet? I tried a lot of parameters of the model but have no progress.

**Comment by oneday88** [comment]
Hi, I upload a new folder ecPointModel for the point forecasting task. Sorry for the mess and thanks a lot for your feedback, I will take some time to refine the total project. For any questions, please let me know immediately.

**Comment by oneday88** [comment]
Hi, I updated the folder for probabilistic forecasting for ec dataset. You can try it in your GPU server, and for any questions. Please let me know.

**Comment by oneday88** [comment]
This issue has been solved.
