### ISSUE TITLE
Query on Train-Test data split

### ISSUE THREAD

**Issue by wasim-hossain** [oneday88/kdd2019deepTCN#2]
Thank you for sharing your valuable efforts. I have one doubt regardinng Train-Test data preparartion. Kindly find my below highlighted comments.

As per my understanding--
**X Index                                        Y Index**
27: 39                                          39: 51
23: 35                                           35: 47
19: 31                                           31: 43
15: 27                                           27: 39
11: 23                                           23: 35
7: 19                                             19: 31
3: 15                                             15: 27

Kindly clarify the indexing details for Train and test data.

 if(i==0):   **##Please confirm whether this will be i <=3**
            testX[i] = series_x
            testY[i] = series_y
            testX2[i,:,:] = covariate_X
            testY2[i,:,:] = covariate_Y
        if(i>2):   **##Please confirm whether this will be i >3**
            trainX[i-3] = series_x
            trainY[i-3] = series_y
            trainX2[i-3] = covariate_X
            trainY2[i-3] = covariate_Y
https://github.com/oneday88/kdd2019deepTCN/blob/master/parts/quantileModel/data_preprocess.ipynb

**Comment by oneday88** [comment]
The codes and descriptions is refined.
