### ISSUE TITLE
Electricity Train Test data preparertion(Preprocessing)

### ISSUE THREAD

**Issue by wasim-hossain** [oneday88/kdd2019deepTCN#3]
As mentioned in paper "Probabilistic Forecasting with Temporal Convolutional Neural Network
", the Electricity Train data has been taken only for Dec (2011, 2012, 2013) and Test data taken for Dec(2014) data. But In preprocessing code It's taking all the last three years data and processing.

Could you please clarify on the same.

**Comment by oneday88** [comment]
Hi, glad to hear from you. Here is the code to select the data of Dec.

### Select the data of the Nov
isNov = trainX2_dt[:,:,3]>=11
trainX_dt = trainX_dt[isNov[:,0]]
trainY_dt = trainY_dt[isNov[:,0]]
trainX2_dt = trainX2_dt[isNov[:,0]]
trainY2_dt = trainY2_dt[isNov[:,0]]

**Comment by wasim-hossain** [comment]
Thank you very much..

Can you please tell me to import nnModels, nnTrainer which python package needs to be install?

**Comment by oneday88** [comment]
Please check the codes such as nnHelper.py nnModels.py.
