### ISSUE TITLE
Hello!   What is the input of bestPointHuber.ipynb？ “new_feature_prepare.pkl" and the result of ECPointHuber.py is around validND 0.8 and VALID nrmse 4.2

### ISSUE THREAD

**Issue by hihihihiwsf** [oneday88/kdd2019deepTCN#4]
BTW, what's the meaning of weight?

**Comment by oneday88** [comment]
Please download the latest codes and follow the document, thanks

**Comment by hihihihiwsf** [comment]
Thanks for your reply! What is the difference between bestPointHuber and ECPointHuber? My training result of ECPointHuber is worse than the result in the paper with the defult parameters.

**Comment by oneday88** [comment]
I quickly create a new fold and git clone the total project. Here is a quick screen of running result in my gpu server.
<img width="1680" alt="Screen Shot 2019-09-24 at 3 21 06 PM" src="https://user-images.githubusercontent.com/7350222/65490076-0b4a4200-dedf-11e9-8426-984d6b95e49e.png">

Again. Please make sure you are running the latest codes; By the way, there is no "weight" in the latest code.
Another example:
<img width="1678" alt="Screen Shot 2019-09-24 at 4 45 06 PM" src="https://user-images.githubusercontent.com/7350222/65496328-d643ec80-deea-11e9-9ec1-e4d310950412.png">

**Comment by oneday88** [comment]
The project is refined.
